version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hS6u&Jm@QxB8zV
      POSTGRES_DB: spreadsheet_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: