default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: hS6u&Jm@QxB8zV
  host: localhost
  port: 5432

development:
  <<: *default
  database: spreadsheet_db

test:
  <<: *default
  database: spreadsheet_test

production:
  <<: *default
  database: spreadsheet_production
